#!/bin/bash
# vim: filetype=sh

# Global variables
sn=tmux

# Functions
usage () {
    echo in usage
    exit 1
}

## open a file that contains a host name per line and then ssh to them.
do_open () {
    local f=$1
    local cnt=1

    tmux new-session -s "$sn" -n main -d

    while read host
    do
        tmux new-window -t "$sn:$cnt" -n ''
        tmux send-keys -t "$sn:$cnt" C-l "ssh $host" C-m
        cnt=$(( $cnt + 1 ))
    done < "$f"

    # attach to main (number 0) window.
    tmux select-window -t "$sn:0"
    tmux -2 attach-session -t "$sn"
}

do_exec () {
    for window in `tmux list-windows -F '#{window_index}' | grep -v '0'`;
    do
        tmux send-keys -t "$sn:$window" C-l "$@" C-m
    done
}

do_close () {
    tmux kill-session -t "$sn"
}

main () {
    local command=$1

    case "$command" in
        "open" )
            local file=$2
            [ ! -f "$file" ] && usage
            do_open "$file"
            ;;
        "exec" )
            local command=$2
            [ "X$command" = "X" ] && usage
            do_exec "$command"
            ;;
        "close" )
            do_close
            ;;
        *)
            usage
            ;;
    esac
}

main "$@"

exit $?
